apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarship
  labels:
    app: scholarship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scholarship
  template:
    metadata:
      labels:
        app: scholarship
    spec:
      containers:
        - name: scholarship
          image: username/scholarship:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5